import { WasteExchange, TextileWaste, CompanyProfile } from "@prisma/client";

type ReceiptTemplateProps = {
  exchange: WasteExchange & {
    textileWaste: TextileWaste & {
      companyProfile: CompanyProfile;
    };
  };
};

export default function ReceiptTemplate({ exchange }: ReceiptTemplateProps) {
  return (
    <div className="min-h-screen bg-white p-8">
      <div className="max-w-3xl mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
        <div className="px-8 py-6">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-teal-600">TexTurn Hub</h1>
            <h2 className="text-xl font-semibold text-gray-700 mt-2">
              Textile Waste Exchange Receipt
            </h2>
          </div>

          {/* Receipt ID and Date */}
          <div className="border-b pb-4 mb-6">
            <p className="text-gray-600">Receipt ID: #{exchange.id}</p>
            <p className="text-gray-600">
              Date: {exchange.created_at.toLocaleDateString()}
            </p>
          </div>

          {/* Exchange Details */}
          <div className="mb-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-3">
              Exchange Details
            </h3>
            <div className="bg-gray-50 p-4 rounded-lg">
              <p className="text-gray-700">
                Status: <span className="capitalize">{exchange.status}</span>
              </p>
              <p className="text-gray-700">
                Title: {exchange.textileWaste.title}
              </p>
              <p className="text-gray-700">
                Company: {exchange.textileWaste.companyProfile.company_name}
              </p>
              <p className="text-gray-700">Quantity: {exchange.quantity}</p>
              {exchange.city && (
                <p className="text-gray-700">City: {exchange.city}</p>
              )}
            </div>
          </div>

          {/* Payment Details */}
          {exchange.price && (
            <div className="mb-6">
              <h3 className="text-lg font-semibold text-gray-800 mb-3">
                Payment Details
              </h3>
              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-gray-700">Price: ${exchange.price}</p>
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center text-gray-500 text-sm mt-8 pt-4 border-t">
            <p>
              This is an official receipt for the textile waste exchange
              transaction.
            </p>
            <p className="mt-2">
              Generated by TexTurn Hub on {new Date().toLocaleDateString()}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
